---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: books-system
data:
  POSTGRES_DB: "books_db"
  POSTGRES_USER: "postgres"
  
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: books-system
type: Opaque
stringData:
  POSTGRES_PASSWORD: "postgres"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: books-system
data:
  MONGO_INITDB_DATABASE: "reviews_db"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: books-system
data:
  RABBITMQ_DEFAULT_USER: "admin"

---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: books-system
type: Opaque
stringData:
  RABBITMQ_DEFAULT_PASS: "admin"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: books-system
data:
  SPRING_PROFILES_ACTIVE: "kubernetes"
