kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: books-system

nodes:
  - role: control-plane
    extraPortMappings:
      # Frontend
      - containerPort: 30000
        hostPort: 3000
        protocol: TCP
      # API Gateway
      - containerPort: 30080
        hostPort: 8080
        protocol: TCP
      # Grafana
      - containerPort: 30001
        hostPort: 3001
        protocol: TCP
      # Zipkin
      - containerPort: 30411
        hostPort: 9411
        protocol: TCP
      # Consul UI
      - containerPort: 30500
        hostPort: 8500
        protocol: TCP
      # RabbitMQ Management
      - containerPort: 30672
        hostPort: 15672
        protocol: TCP
